---
apiVersion: batch/v1
kind: Job
metadata:
  name: vc-test-suite
  labels:
    app: vc-test-suite
spec:
  template:
    metadata:
      labels:
        app: vc-test-suite
    spec:
      terminationGracePeriodSeconds: 1
      containers:
        - name: vc-test-suite
          image: {{ image }}
          imagePullPolicy: IfNotPresent
          env:
            - name: ALLURE_SERVER
              value: {{ ALLURE_SERVER }}
            - name: PROJECT_ID
              value: {{ PROJECT_ID }}
          envFrom:
            - configMapRef:
                name: allure-env
          volumeMounts:
            - mountPath: /vc-test-suite/input.jsonld
              name: input
              subPath: input.jsonld
            - mountPath: /vc-test-suite/config.json
              name: config
              subPath: config.json
            - mountPath: /vc-test-suite/run_test_suite.sh
              name: run-test-suite
              subPath: run_test_suite.sh
            - mountPath: /vc-test-suite/send_results.sh
              name: send-results
              subPath: send_results.sh
            - mountPath: /vc-test-suite/send_results_secure.sh
              name: send-results-secure
              subPath: send_results_secure.sh
          tty: true
          command: [ "./run_test_suite.sh" ]
      volumes:
        - name: input
          configMap:
            name: vc-test-suite
            items:
              - key: input.jsonld
                path: input.jsonld
        - name: config
          configMap:
            name: vc-test-suite
            items:
              - key: config.json
                path: config.json
        - name: run-test-suite
          configMap:
            defaultMode: 0777
            name: vc-test-suite
            items:
              - key: run_test_suite.sh
                path: run_test_suite.sh
        - name: send-results
          configMap:
            defaultMode: 0777
            name: allure-send-results
            items:
              - key: send_results.sh
                path: send_results.sh
        - name: send-results-secure
          configMap:
            defaultMode: 0777
            name: allure-send-results-secure
            items:
              - key: send_results_secure.sh
                path: send_results_secure.sh
      restartPolicy: Never
      concurrencyPolicy: Forbid
  ttlSecondsAfterFinished: 1
  backoffLimit: 0
