---
apiVersion: v1
kind: Service
metadata:
  name: {{ name }}
spec:
  selector:
    app: {{ name }}
  ports:
{% for port in ports %}
    - protocol: TCP
      name: "{{ port.label }}"
      port: {{ port.port }}
      targetPort: {{ port.port }}
{% endfor %}
