---
apiVersion: v1
kind: ConfigMap
metadata:
  name: data-model
data:
  config.json: |
    {
      "generator": "/bin/cat",
      "presentationGenerator": "/bin/cat",
      "generatorOptions": "input.jsonld",
      "sectionsNotSupported": {{ unsupported_features }},
      "jwt":{}
    }
  input.jsonld: '{{ verifiable_credential }}'
  run_test_suite.sh: |
    #! /bin/bash
    npm test
    ./send_results.sh
    npx allure-commandline serve -h 0.0.0.0 -p 8000