---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: {{ $.Values.namespace }}
  name: {{ $.Values.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ $.Values.namespace }}
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ $.Values.namespace }}
subjects:
- kind: ServiceAccount
  namespace: {{ $.Values.namespace }}
  name: {{ $.Values.namespace }}
roleRef:
  kind: ClusterRole
  name: {{ $.Values.namespace }}
  apiGroup: rbac.authorization.k8s.io
