---
apiVersion: v1
kind: ConfigMap
metadata:
  name: allure-send-results-secure
data:
  send_results_secure.sh: |
    #!/bin/bash
    DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
    FILES_TO_SEND=$(ls -dp $DIR/$ALLURE_RESULTS_DIRECTORY/* | grep -v /$)
    if [ -z "$FILES_TO_SEND" ]; then
      exit 1
    fi

    FILES=''
    for FILE in $FILES_TO_SEND; do
      FILES+="-F files[]=@$FILE "
    done

    set -o xtrace

    echo "------------------LOGGING-INTO-ALLURE-SERVICE------------------"
    curl -X POST "$ALLURE_SERVER/allure-docker-service/login" \
      -H 'Content-Type: application/json' \
      -d '{"username": "$SECURITY_USER","password": "$SECURITY_PASS"}' \
      -c cookiesFile -ik

    echo "------------------EXTRACTING-CSRF-ACCESS-TOKEN------------------"
    CRSF_ACCESS_TOKEN_VALUE=$(cat cookiesFile | grep -o 'csrf_access_token.*' | cut -f2)
    echo "csrf_access_token value: $CRSF_ACCESS_TOKEN_VALUE"

    echo "------------------CREATE-PROJECT------------------"
    curl -X POST "$ALLURE_SERVER/allure-docker-service/projects" \
      -H 'Content-Type: application/json' \
      -H "X-CSRF-TOKEN: $CRSF_ACCESS_TOKEN_VALUE" \
      -d '{"id": "$PROJECT_ID"}' \
      -b cookiesFile -ik

    echo "------------------CLEANING-RESULTS------------------"
    curl -X GET "$ALLURE_SERVER/allure-docker-service/clean-results?project_id=$PROJECT_ID" -H  "accept: */*" -b cookiesFile -ik

    echo "------------------SEND-RESULTS------------------"
    curl -X POST "$ALLURE_SERVER/allure-docker-service/send-results?project_id=$PROJECT_ID" \
      -H 'Content-Type: multipart/form-data' \
      -H "X-CSRF-TOKEN: $CRSF_ACCESS_TOKEN_VALUE" \
      -b cookiesFile $FILES -ik

    echo "------------------GENERATE-REPORT------------------"
    RESPONSE=$(curl -X GET "$ALLURE_SERVER/allure-docker-service/generate-report?project_id=$PROJECT_ID" -H "X-CSRF-TOKEN: $CRSF_ACCESS_TOKEN_VALUE" -b cookiesFile $FILES)
    ALLURE_REPORT=$(grep -o '"report_url":"[^"]*' <<< "$RESPONSE" | grep -o '[^"]*$')
