---
namespace: dtt-dev
app_name: dtt-service

deployment:
  image: 
    name: idlaborg/dtt-service
    tag: change_me
  port: 8000

service:
  load_balancer_ip: 10.0.20.225
  port: 8000

ingress:
  domain: api.dtt-dev.idlab.app

environment:
  variables:
    LOCAL: false
    VERSION: development
    DTT_FRONTEND_URL: http://dtt-dev.internal.idlab.org:5000
  secrets:
    SECRET_KEY: '${{ secrets.SECRET_KEY }}'
    OAUTH_GITHUB_CLIENT_ID: '${{ secrets.OAUTH_GITHUB_CLIENT_ID_DEV }}'
    OAUTH_GITHUB_CLIENT_SECRET: '${{ secrets.OAUTH_GITHUB_CLIENT_SECRET_DEV }}'
