---
{{- with .Values.ingress }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: {{ $.Values.namespace }}
  name: {{ $.Values.app_name }}
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: "{{ .subdomain }}.{{ .domain }}"
    http:
      paths:
      - backend:
          service:
            name: {{ $.Values.app_name }}
            port:
              number: {{ $.Values.service.port }}
        path: /
        pathType: ImplementationSpecific
{{- end }}
