---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vc-playground-test-suite
data:
  config.cjs: |
    module.exports = {
      issuer: {
        label: '{{ issuer.label }}',
        id: '{{ issuer.id }}',
        endpoint: '{{ issuer.endpoint }}'
      },
      verifier: {
        label: '{{ verifier.label }}',
        id: '{{ verifier.id }}',
        endpoint: '{{ verifier.endpoint }}'
      },
    };
  run_test_suite.sh: |
    #! /bin/bash
    npm run test
    ./send_results.sh
    npx allure-commandline serve -h 0.0.0.0 -p 8000