---
{{- with .Values.frontend }}
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ $.Values.namespace }}
  name: {{ .label }}
  labels:
    app: {{ .label }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .label }}
  template:
    metadata:
      labels:
        app: {{ .label }}
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: {{ .label }}
        image: "{{ .image }}:{{ .tag }}"
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .port }}
        envFrom:
        - secretRef:
            name: {{ .label }}-env
        - configMapRef:
            name: {{ .label }}-env
{{- end }}