---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vc-test-suite
data:
  config.json: |
    {
      "generator": "/bin/cat",
      "presentationGenerator": "/bin/cat",
      "generatorOptions": "",
      "restapi": {
        "baseUrl": "{{ endpoint }}",
        "generator": "/credentials/issue",
        "presentationGenerator": "/presentations/prove",
        "generatorOptions": {},
        "oauthTokenType": "Bearer",
        "oauthToken": "{{ token }}"
      },
      "sectionsNotSupported": {{ unsupported_features }},
      "jwt":{}
    }
  run_test_suite.sh: |
    #! /bin/bash
    npm run report
    ./send_results.sh
    npx allure-commandline serve -h 0.0.0.0 -p 8000