---
apiVersion: v1
kind: Service
metadata:
  name: vc-test-suite
spec:
  selector:
    app: vc-test-suite
  ports:
    - protocol: TCP
      name: allure-report
      port: 8000
      targetPort: 8000
