name: dtt-applications

on:
  push:
    branches:
      - "main"
      - "DTT-*"

# env:

jobs:
  build-modules:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Docker Login
        run: |
          docker login \
            -u ${{ secrets.DOCKERHUB_USERNAME }} \
            -p ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Run Build Script
        run: |
          cd modules && ./build.sh
